# Exercícios de revisão — Upload de arquivo, Pandas e NumPy

Nesta atividade, você vai usar a planilha **`base_exercicios_alunos_pandas.xlsx`** para praticar leitura de arquivo, exploração de dados, filtros, tratamento simples e uma introdução ao **NumPy**.

> Professor: você pode pedir que os alunos resolvam primeiro sozinhos e depois fazer a correção em sala.

In [3]:
from google.colab import files

uploaded = files.upload()

Saving base_exercicios_alunos_pandas.xlsx to base_exercicios_alunos_pandas.xlsx

## 1. Importando as bibliotecas

Use esta célula para importar as bibliotecas necessárias.

In [6]:
import pandas as pd
import numpy as np

## 2. Carregando o arquivo

Se estiver no **Google Colab**, primeiro envie a planilha.

Se estiver no **Jupyter Notebook**, basta garantir que o arquivo está na mesma pasta do notebook.

In [7]:
# Se estiver no Google Colab, descomente estas linhas:
# from google.colab import files
# uploaded = files.upload()

df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df.head()

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo

In [8]:
#Exercício 1
#Mostre as 5 primeiras linhas da base.
df.head()

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo

In [9]:
#Exercício 2
#Mostre as 5 últimas linhas da base.
df.tail()

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo

In [10]:
#Exercício 3
#Descubra:

#quantidade de linhas e colunas
#nomes das colunas
#tipos de dados
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aluno        30 non-null     int64
 1   nome            30 non-null     object
 2   idade           28 non-null     float64
 3   turma           30 non-null     object
 4   curso           29 non-null     object
 5   nota1           28 non-null     float64
 6   nota2           27 non-null     float64
 7   faltas          28 non-null     float64
 8   cidade          29 non-null     object
 9   uf              29 non-null     object
 10  data_matricula  30 non-null     object
 11  mensalidade     29 non-null     float64
 12  bolsista        29 non-null     object
 13  email           28 non-null     object
 14  status          30 non-null     object
dtypes: float64(5), int64(1), object(9)
memory usage: 3.6+ KB

## 3. Conhecendo a base

### Exercício 1
Mostre as **5 primeiras linhas** da base.

### Exercício 2
Mostre as **5 últimas linhas** da base.

### Exercício 3
Descubra:
- quantidade de linhas e colunas
- nomes das colunas
- tipos de dados

In [13]:
# Resolva Exercício 1
#Mostre as 5 primeiras linhas da base.aqui
df.head()

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo

In [14]:
#Exercício 2
#Mostre as 5 últimas linhas da base.
df.tail()

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo

In [15]:
#Exercício 3
#Descubra:

#quantidade de linhas e colunas
#nomes das colunas
#tipos de dados
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aluno        30 non-null     int64
 1   nome            30 non-null     object
 2   idade           28 non-null     float64
 3   turma           30 non-null     object
 4   curso           29 non-null     object
 5   nota1           28 non-null     float64
 6   nota2           27 non-null     float64
 7   faltas          28 non-null     float64
 8   cidade          29 non-null     object
 9   uf              29 non-null     object
 10  data_matricula  30 non-null     object
 11  mensalidade     29 non-null     float64
 12  bolsista        29 non-null     object
 13  email           28 non-null     object
 14  status          30 non-null     object
dtypes: float64(5), int64(1), object(9)
memory usage: 3.6+ KB

## 4. Seleção de colunas

### Exercício 4
Mostre apenas as colunas:
- `nome`
- `curso`
- `turma`
- `nota1`

### Exercício 5
Crie um novo DataFrame chamado `df_notas` contendo:
- `nome`
- `nota1`
- `nota2`
- `faltas`

In [2]:
#Exercício 4
#Mostre apenas as colunas:

#nome
#curso
#turma
#nota1
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df[["nome", "curso", "turma","nota1", ]]

FileNotFoundError: [Errno 2] No such file or directory: 'base_exercicios_alunos_pandas.xlsx'

In [1]:
#Exercício 5
#Crie um novo DataFrame chamado df_notas contendo:

#nome
#nota1
#nota2
#faltas
import pandas as pd

# criando o DataFrame
df_notas = pd.DataFrame({
    "nome": ["Ana", "Bruno", "Carlos", "Daniela"],
    "nota1": [8.5, 7.0, 6.5, 9.0],
    "nota2": [9.0, 6.5, 7.0, 8.5],
    "faltas": [2, 5, 3, 1]
})

# exibindo
print(df_notas)

      nome  nota1  nota2  faltas
0      Ana    8.5    9.0       2
1    Bruno    7.0    6.5       5
2   Carlos    6.5    7.0       3
3  Daniela    9.0    8.5       1

## 5. Filtros

### Exercício 6
Filtre apenas os alunos do curso **IA**.

### Exercício 7
Filtre apenas os alunos com `nota1` maior ou igual a **7**.

### Exercício 8
Filtre apenas os alunos da turma **B** e do curso **Dados**.

### Exercício 9
Filtre os alunos com mais de **5 faltas**.

In [19]:
# Resolva aquiExercício 6
#Filtre apenas os alunos do curso IA.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df[df["curso"] == "IA"]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo

In [22]:
#Exercício 7
#Filtre apenas os alunos com nota1 maior ou igual a 7.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df[df["nota1"] >= 7]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,SIM,gabriela.nunes@email.com,Ativo
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo

In [23]:
#Exercício 8
#Filtre apenas os alunos da turma B e do curso Dados.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df[(df["turma"] == "B") & (df["curso"] == "Dados")]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo

In [24]:
#Exercício 9
#Filtre os alunos com mais de 5 faltas.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df[df["faltas"] > 5]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco

## 6. Valores nulos

### Exercício 10
Verifique quantos valores nulos existem em cada coluna.

### Exercício 11
Mostre apenas as linhas onde a coluna `idade` está nula.

### Exercício 12
Preencha os valores nulos de `nota1` com a média da coluna `nota1`.

In [25]:
# Resolva aqui
#Exercício 10
#Verifique quantos valores nulos existem em cada coluna.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df.isnull().sum()

id_aluno          0
nome              0
idade             2
turma             0
curso             1
nota1             2
nota2             3
faltas            2
cidade            1
uf                1
data_matricula    0
mensalidade       1
bolsista          1
email             2
status            0
dtype: int64

In [26]:
#Exercício 11
#Mostre apenas as linhas onde a coluna idade está nula.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df[df["idade"].isnull()]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo

## 7. Tratamento de texto e padronização

### Exercício 13
Padronize a coluna `bolsista` para ficar apenas com:
- `Sim`
- `Não`

Dica: existem valores como `SIM`, `sim`, `Nao`.

### Exercício 14
Padronize a coluna `uf` para letras maiúsculas.

### Exercício 15
Padronize a coluna `cidade` no formato título.
Exemplo:
- `brasília` → `Brasília`

In [33]:
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")

# 1. Preenche valores NaN na coluna 'bolsista' com 'Não'
# Assumimos que NaN neste contexto significa que o aluno não é bolsista.
df["bolsista"] = df["bolsista"].fillna('Não')

# 2. Converte todas as entradas para minúsculas para padronização de case
df["bolsista"] = df["bolsista"].str.lower()

# 3. Mapeia as variações para 'Sim' ou 'Não' padronizados
df["bolsista"] = df["bolsista"].replace({
    "sim": "Sim",
    "nao": "Não",
    "não": "Não" # Garante que 'não' após lower() seja mapeado
})

display(df)

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,Sim,gabriela.nunes@email.com,Ativo
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Não,henrique.silva@email.com,Ativo
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
9,10,João Pedro,19.0,A,Desenvolvimento,6.7,6.2,4.0,Aparecida de Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.9,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,Não,NaN,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,Sim,daniela.pires@email.com,Ativo

In [35]:
#Exercício 14
#Padronize a coluna uf para letras maiúsculas.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df["uf"] = df["uf"].str.upper()
display(df)

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,SIM,gabriela.nunes@email.com,Ativo
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
9,10,João Pedro,19.0,A,Desenvolvimento,6.7,6.2,4.0,Aparecida de Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,DF,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.9,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo

In [36]:
#Padronize a coluna cidade no formato título. Exemplo:

#brasília → Brasília
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df["cidade"] = df["cidade"].str.title()
display(df)

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,SIM,gabriela.nunes@email.com,Ativo
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
9,10,João Pedro,19.0,A,Desenvolvimento,6.7,6.2,4.0,Aparecida De Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,Brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.9,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo

## 8. Criando novas colunas

### Exercício 16
Crie uma coluna chamada `media` com a média entre `nota1` e `nota2`.

### Exercício 17
Crie uma coluna chamada `aprovado`:
- `True` para média maior ou igual a **7**
- `False` caso contrário

### Exercício 18
Crie uma coluna chamada `situacao_faltas`:
- `Alto risco` para mais de 10 faltas
- `Atenção` para 6 a 10 faltas
- `Ok` para até 5 faltas

In [38]:
# Resolva aqui
#Exercício 16
#Crie uma coluna chamada media com a média entre nota1 e nota2.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df["media"] = (df["nota1"] + df["nota2"]) / 2
display(df)

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo,6.75
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo,NaN
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco,5.75
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo,7.95
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo,4.75
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,SIM,gabriela.nunes@email.com,Ativo,8.40
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo,NaN
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo,9.60
9,10,João Pedro,19.0,A,Desenvolvimento,6.7,6.2,4.0,Aparecida de Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco,6.45
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo,7.00
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo,4.00
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo,8.95
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco,6.35
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo,9.90
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco,6.10
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo,7.80
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo,NaN
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo,7.95
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco,5.10
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo,8.20
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.9,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo,7.00
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo,2.75
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo,9.05
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo,8.50
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco,5.95
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo,7.40
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo,NaN
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo,8.65

In [42]:
#Exercício 17
#Crie uma coluna chamada aprovado:

#True para média maior ou igual a 7
#False caso contrário
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df["media"] = (df["nota1"] + df["nota2"]) / 2 # Garante que a coluna 'media' seja criada
df["aprovado"] = df["media"] >= 7
display(df)

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media,aprovado
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75,True
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo,6.75,False
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo,NaN,False
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco,5.75,False
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo,7.95,True
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo,4.75,False
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,SIM,gabriela.nunes@email.com,Ativo,8.40,True
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo,NaN,False
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo,9.60,True
9,10,João Pedro,19.0,A,Desenvolvimento,6.7,6.2,4.0,Aparecida de Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco,6.45,False
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo,7.00,True
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo,4.00,False
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo,8.95,True
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco,6.35,False
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo,9.90,True
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco,6.10,False
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo,7.80,True
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo,NaN,False
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo,7.95,True
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco,5.10,False
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo,8.20,True
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.9,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo,7.00,True
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo,2.75,False
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo,9.05,True
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo,8.50,True
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco,5.95,False
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75,True
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo,7.40,True
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo,NaN,False
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo,8.65,True

In [49]:
#Exercício 18
#Crie uma coluna chamada situacao_faltas:

#Alto risco para mais de 10 faltas
#Atenção para 6 a 10 faltas
#Ok para até 5 faltas
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df["situacao_faltas"] = df["faltas"].apply(lambda x: "Alto risco" if x > 10 else ("Atenção" if x >= 6 else "Ok"))
display(df)

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,situacao_faltas
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,Ok
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo,Ok
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo,Ok
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco,Atenção
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo,Ok
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo,Alto risco
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,SIM,gabriela.nunes@email.com,Ativo,Ok
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo,Ok
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo,Ok
9,10,João Pedro,19.0,A,Desenvolvimento,6.7,6.2,4.0,Aparecida de Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco,Ok
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo,Atenção
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo,Alto risco
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo,Ok
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco,Atenção
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo,Ok
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco,Atenção
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo,Ok
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo,Alto risco
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo,Ok
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco,Atenção
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo,Ok
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.9,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo,Ok
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo,Alto risco
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo,Ok
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo,Ok
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco,Alto risco
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,Ok
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo,Ok
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo,Ok
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo,Ok

## 9. Ordenação, contagem e agrupamento

### Exercício 19
Ordene os alunos pela coluna `media`, do maior para o menor.

### Exercício 20
Conte quantos alunos existem em cada curso.

### Exercício 21
Mostre a média de `nota1` por curso.

### Exercício 22
Mostre a média de faltas por turma.

In [52]:
# Resolva aqui
#Ordenação, contagem e agrupamento
#Exercício 19
#Ordene os alunos pela coluna media, do maior para o menor.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df["media"] = (df["nota1"] + df["nota2"]) / 2 # Recalcula a coluna 'media'
df = df.sort_values(by="media", ascending=False)
display(df)

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo,9.90
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo,9.60
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo,9.05
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo,8.95
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo,8.65
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo,8.50
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,SIM,gabriela.nunes@email.com,Ativo,8.40
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo,8.20
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo,7.95
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo,7.95
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo,7.80
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo,7.40
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.9,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo,7.00
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo,7.00
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo,6.75
9,10,João Pedro,19.0,A,Desenvolvimento,6.7,6.2,4.0,Aparecida de Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco,6.45
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco,6.35
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco,6.10
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco,5.95
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco,5.75
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco,5.10
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo,4.75
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo,4.00
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo,2.75
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo,NaN
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo,NaN
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo,NaN
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo,NaN

In [53]:
#Exercício 20
#Conte quantos alunos existem em cada curso.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
curso_counts = df["curso"].value_counts()
display(curso_counts)

curso
IA                 11
Dados              10
Desenvolvimento     8
Name: count, dtype: int64

In [54]:
#Exercício 21
#Mostre a média de nota1 por curso.

df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
media_nota1_por_curso = df.groupby("curso")["nota1"].mean()
display(media_nota1_por_curso)

curso
Dados              7.777778
Desenvolvimento    6.600000
IA                 6.690000
Name: nota1, dtype: float64

In [55]:
#Exercício 22
#Mostre a média de faltas por turma.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
media_faltas_por_turma = df.groupby("turma")["faltas"].mean()
display(media_faltas_por_turma)

turma
A    3.70
B    4.90
C    7.75
Name: faltas, dtype: float64

## 10. Duplicatas e qualidade dos dados

### Exercício 23
Verifique se existem linhas duplicadas.

### Exercício 24
Remova as duplicatas e salve em um novo DataFrame chamado `df_limpo`.

### Exercício 25
Mostre os registros com emails possivelmente inválidos.
Dica: procure emails sem `@` ou sem `.com`.

In [56]:
# Resolva aqui
#Exercício 23
#Verifique se existem linhas duplicadas.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df = df.drop_duplicates()
display(df)

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,SIM,gabriela.nunes@email.com,Ativo
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
9,10,João Pedro,19.0,A,Desenvolvimento,6.7,6.2,4.0,Aparecida de Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.9,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo

In [58]:
#Exercício 24
#Remova as duplicatas e salve em um novo DataFrame chamado df_limpo.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df_limpo = df.drop_duplicates()
display(df_limpo)

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,SIM,gabriela.nunes@email.com,Ativo
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
9,10,João Pedro,19.0,A,Desenvolvimento,6.7,6.2,4.0,Aparecida de Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.9,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo

In [61]:
#Exercício 25
#Mostre os registros com emails possivelmente inválidos. Dica: procure emails sem @ ou sem .com.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df_invalido = df[~df["email"].str.contains("@", na=False) | ~df["email"].str.contains(".com", na=False)]
display(df_invalido)

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
9,10,João Pedro,19.0,A,Desenvolvimento,6.7,6.2,4.0,Aparecida de Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo

## 11. Salvando um novo arquivo

### Exercício 26
Salve o DataFrame tratado em um novo arquivo Excel chamado:
`base_tratada_alunos.xlsx`

In [63]:
# Resolva aqui
#Exercício 26
#Salve o DataFrame tratado em um novo arquivo Excel chamado: base_tratada_alunos.xlsx
# Assuming df_limpo from Exercise 24 is the treated DataFrame
df_limpo.to_excel("base_tratada_alunos.xlsx", index=False)

## 12. Introdução ao NumPy

### Exercício 27
Crie um array NumPy com os valores da coluna `nota1`, removendo os nulos.

### Exercício 28
Com esse array, calcule:
- média
- maior valor
- menor valor
- soma

### Exercício 29
Some **1 ponto** em todas as notas do array.

### Exercício 30
Mostre apenas as notas maiores que **7** usando NumPy.

In [64]:
# Resolva aqui
#Exercício 27
#Crie um array NumPy com os valores da coluna nota1, removendo os nulos.
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
nota1_array = df["nota1"].dropna().to_numpy()
display(nota1_array)

array([ 8.5,  6. ,  9.2,  5.5,  7.8,  4. ,  8. ,  9.5,  6.7,  7. ,  3.5,
        8.8,  5.9, 10. ,  6.3,  7.4,  4.8,  7.9,  5. ,  8.1,  6.9,  2.5,
        9.1,  8.3,  6.1,  8.5,  7.2,  8.4])

## 13. Desafio final

### Exercício 31 — Desafio
Monte uma análise final respondendo:

1. Quantos alunos há em cada curso?
2. Qual curso tem a maior média de `nota1`?
3. Quantos alunos têm mais de 10 faltas?
4. Quantos alunos são bolsistas?
5. Há dados faltando? Em quais colunas?
6. Há duplicatas?
7. Gere um DataFrame final apenas com:
   - `nome`
   - `curso`
   - `media`
   - `aprovado`

Depois, ordene esse DataFrame pela `media` em ordem decrescente.

In [65]:
# Resolva aqui

# Carrega o DataFrame novamente para garantir o estado inicial
df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")

# Garante que as colunas 'bolsista' e 'uf' estejam padronizadas como nos exercícios anteriores
df["bolsista"] = df["bolsista"].fillna('Não')
df["bolsista"] = df["bolsista"].str.lower()
df["bolsista"] = df["bolsista"].replace({"sim": "Sim", "nao": "Não", "não": "Não"})
df["uf"] = df["uf"].str.upper()
df["cidade"] = df["cidade"].str.title()

# 1. Quantos alunos há em cada curso?
print("1. Quantos alunos há em cada curso?")
display(df["curso"].value_counts())
print("\n" + "-"*30 + "\n")

# Recalcula 'media' e 'aprovado' para garantir que estejam presentes e atualizados
df["media"] = (df["nota1"] + df["nota2"]) / 2
df["aprovado"] = df["media"] >= 7

# 2. Qual curso tem a maior média de nota1?
print("2. Qual curso tem a maior média de nota1?")
media_nota1_por_curso = df.groupby("curso")["nota1"].mean()
curso_maior_media_nota1 = media_nota1_por_curso.idxmax()
display(f"O curso com a maior média de nota1 é: {curso_maior_media_nota1} ({media_nota1_por_curso.max():.2f})")
print("\n" + "-"*30 + "\n")

# 3. Quantos alunos têm mais de 10 faltas?
print("3. Quantos alunos têm mais de 10 faltas?")
alunos_alto_risco_faltas = df[df["faltas"] > 10].shape[0]
display(f"Número de alunos com mais de 10 faltas: {alunos_alto_risco_faltas}")
print("\n" + "-"*30 + "\n")

# 4. Quantos alunos são bolsistas?
print("4. Quantos alunos são bolsistas?")
alunos_bolsistas = df[df["bolsista"] == "Sim"].shape[0]
display(f"Número de alunos bolsistas: {alunos_bolsistas}")
print("\n" + "-"*30 + "\n")

# 5. Há dados faltando? Em quais colunas?
print("5. Há dados faltando? Em quais colunas?")
dados_faltando = df.isnull().sum()
display(dados_faltando[dados_faltando > 0])
print("\n" + "-"*30 + "\n")

# 6. Há duplicatas?
print("6. Há duplicatas?")
duplicatas_count = df.duplicated().sum()
display(f"Há duplicatas na base de dados: {duplicatas_count > 0} (Total: {duplicatas_count})")
print("\n" + "-"*30 + "\n")

# 7. Gere um DataFrame final
print("7. Gerando DataFrame final (nome, curso, media, aprovado) e ordenando pela média:")
df_final = df[["nome", "curso", "media", "aprovado"]]
df_final = df_final.sort_values(by="media", ascending=False)
display(df_final.head(10)) # Mostra as 10 primeiras linhas do DataFrame final

1. Quantos alunos há em cada curso?

curso
IA                 11
Dados              10
Desenvolvimento     8
Name: count, dtype: int64

------------------------------

2. Qual curso tem a maior média de nota1?

'O curso com a maior média de nota1 é: Dados (7.78)'

------------------------------

3. Quantos alunos têm mais de 10 faltas?

'Número de alunos com mais de 10 faltas: 5'

------------------------------

4. Quantos alunos são bolsistas?

'Número de alunos bolsistas: 16'

------------------------------

5. Há dados faltando? Em quais colunas?

idade          2
curso          1
nota1          2
nota2          3
faltas         2
cidade         1
uf             1
mensalidade    1
email          2
media          4
dtype: int64

------------------------------

6. Há duplicatas?

'Há duplicatas na base de dados: False (Total: 0)'

------------------------------

7. Gerando DataFrame final (nome, curso, media, aprovado) e ordenando pela média:

              nome            curso  media  aprovado
14  Olivia Martins               IA   9.90      True
8    Isabela Costa            Dados   9.60      True
23   Ximena Duarte            Dados   9.05      True
12    Mariana Reis            Dados   8.95      True
26       Ana Clara               IA   8.75      True
0        Ana Clara               IA   8.75      True
29   Daniela Pires  Desenvolvimento   8.65      True
24    Yasmin Rocha               IA   8.50      True
6   Gabriela Nunes  Desenvolvimento   8.40      True
20   Ursula Ferraz            Dados   8.20      True

In [ ]:
# Resolva aqui

## 14. Espaço para correção

Professor: aqui você pode ir resolvendo os exercícios em sala após os alunos tentarem.

In [ ]:
# Correção do professor